name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:   
    branches: [ master ]
    
jobs:
  test-and-push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore COMTRADE.sln
      
      - name: Build
        run: dotnet build COMTRADE.sln --no-restore --configuration Release
  
      - name: Run Tests
        run: dotnet test COMTRADE.Tests/COMTRADE.Tests.csproj --no-build --configuration Release

      - name: Push to GitHub
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push origin master
